name: Filipe Dechamps

on:
  
  #schedule: 
  #  - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  read_news:
    name: Read All news in Filipe Dechamps Newsletter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
          architecture: 'x64'
          
      - name: Install Depencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip freeze
          
      - name: Run script
        run: python newsletter_dechamps.py  ${{ secrets.MAIL_ADDRESS }}  ${{ secrets.DISCORD_WEBHOOK }}
